#5a) Using "try" and "except" to handle exceptions
try:
    print(0 / 0)
except ZeroDivisionError:
    print("divide by zero... NUH UH")